Adding footer (not responsive)
azharnian/my-igs pull request #14
Opened 2023-11-24 03:40 UTC by syacia09

2023-11-24 04:19 UTC, azharnian commented on clients/pages/LoginPage/assets/Icon.png
pakai svg icon saja ya @NelsenJ @syacia09 , cek di sini 
https://boxicons.com/

2023-11-24 04:20 UTC, azharnian commented on clients/pages/LoginPage/assets/Logo.png
Ganti dengan logo IGS yg sudah di ubah dengan warna putih untuk backgound gelap

2023-11-24 04:21 UTC, azharnian commented on clients/pages/LoginPage/assets/Photo.png
ganti gambar lain dengan resolusi sama

2023-11-24 04:21 UTC, azharnian commented on clients/pages/LoginPage/assets/down-arrow-4846.png
pakai boxicons

2023-11-24 04:22 UTC, azharnian commented on clients/pages/LoginPage/assets/image.png
input form untuk captcha hilangka saja

2023-11-24 04:22 UTC, azharnian commented on clients/pages/LoginPage/assets/permata-white.2fd43bfc.svg.png
ganti dengan logo igs yg putih

2023-11-24 04:32 UTC, azharnian commented on clients/pages/LoginPage/login.css
untuk penggunaan css, sr minta diperbaiki misal ada kelas container di dalam header
biasanya dibuat
header .container

untuk sekrang sr minta dibuat
div container di dalam header untuk menjadi .header--container (menggunakan double dash agar saat nanti kita pakai css framework tidak conflict)

jadi saat selector di css menjadi

header .header--container

2023-11-24 04:33 UTC, azharnian requested changes
Mohon diperbaiki terlebih dahulu ya

2023-11-24 04:36 UTC, NelsenJ commented on clients/pages/LoginPage/assets/Icon.png
siap sir

2023-11-24 04:52 UTC, NelsenJ commented on clients/pages/LoginPage/login.css
sir kalau div yang didalam container jadi 
header .header--container .header--container--namadiv atau gimana ya sir?

2023-11-24 06:19 UTC, NelsenJ commented on clients/pages/LoginPage/login.css
dan juga di htmlnya diganti juga kan sir?

2023-11-25 11:57 UTC, azharnian commented
Untuk form login, ada issue, jika menggunakan for di label form, pastikan sesuai id-nya di inputnys
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

Kemudian untuk mobile view, untuk layar dengan height kecil, footer menghalangi form. Webnya bisa dicoba dihandphone ukuran kecil melalui situs ini
https://azharnian.github.io/my-igs/clients/pages/LoginPage/login.html
perbaikin lagi ya, dan Ditunggu perubahan assetnya jg

2023-11-28 02:44 UTC, azharnian approved these changes

2023-11-28 02:45 UTC, merged