Login
azharnian/my-igs pull request #18
Opened 2023-11-28 14:33 UTC by NelsenJ

Almost Cloned
Responsive = Almost Done(HideNav almost done)
Language Nav = Stuck
No Modification

2023-11-29 02:42 UTC, azharnian requested changes
Perbaiki pull branchnya, belum benar

2023-11-29 14:04 UTC, NelsenJ commented
sudah diperbaiki di bagian form sm warna telah diubah menurut kmi yg cocok sir, trus tinggal dikit lagi butuh responsive di bagian 1000px sampai 500px sedikit setelah itu animasi di bagian hide nav jg

2023-11-30 00:14 UTC, azharnian commented
logo saat mobile view, tampak kecil dan tidak proposional, kemudian setelah selesai buatkan Component htmlnya di folder component

2023-12-20 04:11 UTC, azharnian approved these changes

2023-12-20 04:11 UTC, merged